FROM python:3.9-slim

# Set the working directory
WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Install the dependencies
RUN pip install --no-cache-dir python-telegram-bot yt-dlp python-dotenv

# Copy the rest of the application code
RUN curl -o telegram-bot.py https://raw.githubusercontent.com/SiestaCat/ytdlp-bot/refs/heads/main/telegram-bot.py

# Command to run the application
CMD ["python", "telegram-bot.py"]